### ISSUE TITLE
[BUG] v3.57.0 now require project and config arguments

### ISSUE THREAD

**Issue by glarivie** [DopplerHQ/cli#384] opened 2023-04-21 11:18 UTC
**Describe the bug**
Cli v3.57.0 introduce a breaking-change and now require `--projet` and `--config` arguments to fetch secrets but not before (with cli v3.56.2 for exemple). Same behavior with all commands, not only `doppler secrets`.

**To Reproduce**
##### with cli v3.57.0 :
```sh
➜ cd <folder>
➜ doppler setup --token=*** --project=my_project --config=dev
➜ doppler secrets --only-names

Unable to fetch secret names
Doppler Error: You must specify a project
```
```sh
➜ doppler secrets --project=my_project --only-names

Unable to fetch secret names
Doppler Error: You must specify a config
```
```sh
➜ doppler secrets --project=my_project --config=dev --only-names

┌────────────────────────────────────┐
│ NAME                               │
├────────────────────────────────────┤
│ SECRET_KEY                         │
└────────────────────────────────────┘
```

**Expected behavior**
##### with cli v3.56.2 :
```sh
➜ cd <folder>
➜ doppler setup --token=*** --project=my_project --config=dev
➜ doppler secrets --only-names

┌────────────────────────────────────┐
│ NAME                               │
├────────────────────────────────────┤
│ SECRET_KEY                         │
└────────────────────────────────────┘
```

**Desktop (please complete the following information):**
 - OS: macOS 13.1 (local) & Ubuntu 22.04.2 64bits (github actions)

**CLI Version:**
Version 3.57.0

**Comment by Gabrielpanga** [comment] 2023-04-21 11:32
Also since we are using doppler directly on GH actions and automatically updates to latest version of cli, without the ability to specify the cli version, this is breaking all our pipelines.

**Comment by glarivie** [comment] 2023-04-21 13:44
I don't have the problem with interactive `setup`. Only when using cli with arguments.

**Comment by Piccirello** [comment] 2023-04-22 00:38
Duplicate of #385

**Closed as completed by Piccirello** 2023-04-22 00:38 UTC
Labels: bug
